//
// Created by Olcay Taner YILDIZ on 10.02.2024.
//

#ifndef SYNTACTICPARSER_RULETYPE_H
#define SYNTACTICPARSER_RULETYPE_H

enum class RuleType{
    TERMINAL, SINGLE_NON_TERMINAL, TWO_NON_TERMINAL, MULTIPLE_NON_TERMINAL
};
#endif //SYNTACTICPARSER_RULETYPE_H
